// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rmit.Asr.Application.Data;

namespace Rmit.Asr.Application.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rmit.Asr.Application.Models.Room", b =>
                {
                    b.Property<string>("RoomID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RoomID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Rmit.Asr.Application.Models.Slot", b =>
                {
                    b.Property<string>("RoomID");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("StaffID")
                        .IsRequired();

                    b.Property<string>("StudentID");

                    b.HasKey("RoomID", "StartTime");

                    b.HasIndex("StaffID");

                    b.HasIndex("StudentID");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("Rmit.Asr.Application.Models.Staff", b =>
                {
                    b.Property<string>("StaffID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("StaffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Rmit.Asr.Application.Models.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Rmit.Asr.Application.Models.Slot", b =>
                {
                    b.HasOne("Rmit.Asr.Application.Models.Room", "Room")
                        .WithMany("Slots")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rmit.Asr.Application.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rmit.Asr.Application.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");
                });
#pragma warning restore 612, 618
        }
    }
}
